import type { AlloQuestion } from './types';
import type { DifficultyLevel } from '@/lib/types';

export const QUESTIONS: AlloQuestion[] = [
  // ── ORTHOGRAPHE ──────────────────────────────────────────────────────────

  {
    id: 'ortho-au-maire',
    type: 'orthography',
    customerEmoji: '👩',
    customerName: 'Schlagonie B.',
    customerMessage: "Je veux déposer une plainte officielle, c'est scandaleux !",
    responseBefore: 'Nous transmettrons votre demande directement ',
    responseAfter: ' de La Baffe pour traitement prioritaire.',
    options: ['au maire', 'du maire', 'à le maire', 'de le maire'],
    correct: 'au maire',
    explanation: "'à + le' → 'au'. On transmet quelque chose À quelqu'un (direction). 'du maire' = appartenance ('le bureau du maire', 'la fille du maire').",
    points: 100,
    minLevel: 1,
  },
  {
    id: 'ortho-a-avoir',
    type: 'orthography',
    customerEmoji: '😤',
    customerName: 'Bernard T.',
    customerMessage: "Mon colis est introuvable depuis 3 jours, c'est inacceptable !",
    responseBefore: 'Je vois que votre colis ',
    responseAfter: ' bien été enregistré dans notre système.',
    options: ['a', 'à'],
    correct: 'a',
    explanation: "'a' = verbe avoir (3ème pers. sing.). 'à' est une préposition. Test : remplacez par 'avait' → 'avait bien été enregistré' ✓ → c'est un verbe.",
    points: 100,
    minLevel: 1,
  },
  {
    id: 'ortho-ces-affaires',
    type: 'orthography',
    customerEmoji: '🧑',
    customerName: 'Maxime R.',
    customerMessage: "J'ai laissé mes affaires au bureau, elles ont disparu !",
    responseBefore: '',
    responseAfter: " affaires ont été retrouvées par l'équipe de nettoyage.",
    options: ['Ces', 'Ses', "C'est", "S'est"],
    correct: 'Ces',
    explanation: "'Ces' = adjectif démonstratif pluriel (remplacez par 'les' : 'les affaires'). 'Ses' serait pour 'ses propres affaires'.",
    points: 100,
    minLevel: 1,
  },
  {
    id: 'ortho-votre',
    type: 'orthography',
    customerEmoji: '👴',
    customerName: 'Gérard M.',
    customerMessage: "Je veux savoir le statut de ma commande numéro 4521.",
    responseBefore: 'Merci de confirmer ',
    responseAfter: ' numéro de commande, monsieur.',
    options: ['votre', 'vôtre'],
    correct: 'votre',
    explanation: "'Votre' = déterminant possessif (devant un nom). 'Vôtre' est un pronom : 'c'est le vôtre'. Ici il y a un nom ('numéro') donc 'votre'.",
    points: 100,
    minLevel: 1,
  },
  {
    id: 'ortho-a-la-mairie',
    type: 'orthography',
    customerEmoji: '🏛️',
    customerName: 'Claudette B.',
    customerMessage: "C'est pour une demande administrative urgente !",
    responseBefore: 'Je vous transfère ',
    responseAfter: ' mairie pour traiter votre demande.',
    options: ['à la', 'de la', 'au', 'du'],
    correct: 'à la',
    explanation: "'à + la' reste 'à la' (féminin, pas de contraction). 'au' = à + le (masculin seulement). 'Mairie' est féminin.",
    points: 100,
    minLevel: 1,
  },
  {
    id: 'ortho-au-service',
    type: 'orthography',
    customerEmoji: '💼',
    customerName: 'Frédéric L.',
    customerMessage: "C'est urgent, redirigez-moi vers la facturation immédiatement !",
    responseBefore: 'Je vous transfère ',
    responseAfter: ' service facturation tout de suite.',
    options: ['au', 'du', 'à le', 'de le'],
    correct: 'au',
    explanation: "'à + le' → 'au' (masculin). 'Du' = 'de + le' serait pour 'je reviens du service'. Ici c'est une direction (à) = 'au'.",
    points: 100,
    minLevel: 2,
  },
  {
    id: 'ortho-rappelle',
    type: 'orthography',
    customerEmoji: '📱',
    customerName: 'Nathalie P.',
    customerMessage: "Vous pouvez me rappeler dans l'heure ?",
    responseBefore: 'Bien sûr, je vous ',
    responseAfter: ' dans les 5 prochaines minutes !',
    options: ['rappelle', 'rappel', 'rappelles', 'rappeler'],
    correct: 'rappelle',
    explanation: "1ère personne du singulier des verbes en -er : 'je rappelle' (sans 's'). 'Rappel' est un nom, 'rappeler' un infinitif.",
    points: 100,
    minLevel: 1,
  },
  {
    id: 'ortho-ou-sans-accent',
    type: 'orthography',
    customerEmoji: '📧',
    customerName: 'Sylvie V.',
    customerMessage: "Comment puis-je vous contacter si j'ai un problème ?",
    responseBefore: 'Vous pouvez nous joindre par téléphone ',
    responseAfter: ' par e-mail, 7 jours sur 7.',
    options: ['ou', 'où'],
    correct: 'ou',
    explanation: "'ou' = conjonction de coordination (= 'ou bien'). 'où' = adverbe de lieu. Test : peut-on remplacer par 'ou bien' ? Oui → pas d'accent.",
    points: 100,
    minLevel: 2,
  },
  {
    id: 'ortho-leurs',
    type: 'orthography',
    customerEmoji: '👥',
    customerName: 'Association Vosges+',
    customerMessage: "Tous nos membres ont reçu une mauvaise réponse de votre équipe !",
    responseBefore: 'Nous avons bien reçu ',
    responseAfter: ' réclamations et nous nous en excusons.',
    options: ['leurs', 'leur'],
    correct: 'leurs',
    explanation: "'Leurs réclamations' = plusieurs réclamations de plusieurs personnes → pluriel. 'Leur' reste invariable quand c'est un pronom objet ('je leur réponds').",
    points: 100,
    minLevel: 2,
  },
  {
    id: 'ortho-c-est',
    type: 'orthography',
    customerEmoji: '😕',
    customerName: 'Kevin S.',
    customerMessage: "On m'a orienté vers vous, j'espère qu'on m'a bien redirigé !",
    responseBefore: '',
    responseAfter: " bien notre ligne d'assistance, vous avez bien fait d'appeler !",
    options: ["C'est", "S'est", 'Ces', 'Ses'],
    correct: "C'est",
    explanation: "'C'est' = 'cela est'. Test : remplacez par 'cela est' → 'cela est bien notre ligne' ✓. 'S'est' = verbe pronominal (il s'est trompé).",
    points: 100,
    minLevel: 2,
  },
  {
    id: 'ortho-ont',
    type: 'orthography',
    customerEmoji: '😠',
    customerName: 'Martine G.',
    customerMessage: "C'est pas normal ! Tous mes voisins vivent exactement la même chose !",
    responseBefore: 'Vos voisins ',
    responseAfter: " bien signalé ce problème, nous le traitons en priorité.",
    options: ['ont', 'on'],
    correct: 'ont',
    explanation: "'ont' = verbe avoir, 3ème pers. pluriel. Test : remplacez par 'ils ont' → 'ils ont bien signalé' ✓. 'on' est un pronom sujet ('on dit que...').",
    points: 100,
    minLevel: 2,
  },
  {
    id: 'ortho-quelle',
    type: 'orthography',
    customerEmoji: '🤔',
    customerName: 'Thomas H.',
    customerMessage: "Je veux être rappelé mais je suis pas toujours disponible.",
    responseBefore: '',
    responseAfter: ' est votre plage horaire préférée pour être recontacté ?',
    options: ['Quelle', 'Quel', "Qu'elle", "Qu'il"],
    correct: 'Quelle',
    explanation: "'Plage horaire' est féminin → 'quelle' (accord). 'Quel' serait pour un nom masculin. Test d'accord : 'quelle plage' ✓",
    points: 100,
    minLevel: 3,
  },
  {
    id: 'ortho-de-son-pere',
    type: 'orthography',
    customerEmoji: '👧',
    customerName: 'Emma D.',
    customerMessage: "Mon père travaille pour la mairie, il mérite un meilleur service !",
    responseBefore: "Nous notons que vous êtes la fille ",
    responseAfter: " père. Nous traitons votre demande en priorité.",
    options: ['de son', 'à son', 'du son', 'au son'],
    correct: 'de son',
    explanation: "L'appartenance (filiation) se marque toujours avec 'de' : 'la fille de son père'. 'À' indique un lieu ou un destinataire, pas l'appartenance.",
    points: 100,
    minLevel: 1,
  },
  {
    id: 'ortho-du-maire-fille',
    type: 'orthography',
    customerEmoji: '👩‍💼',
    customerName: 'Schlagonie B.',
    customerMessage: "Je représente la mairie de La Baffe, un peu de considération s'il vous plaît !",
    responseBefore: 'Bien reçu, madame. Nous accordons une attention particulière à la fille ',
    responseAfter: ' de La Baffe dans notre traitement.',
    options: ['du maire', 'au maire', 'de le maire', 'à le maire'],
    correct: 'du maire',
    explanation: "'de + le' → 'du' (contraction obligatoire, masculin). 'Au maire' = à + le → pour parler AU maire (direction). Ici : la fille appartenant au maire = 'fille du maire'.",
    points: 100,
    minLevel: 3,
  },
  {
    id: 'ortho-de-la-secretaire',
    type: 'orthography',
    customerEmoji: '🏢',
    customerName: 'Pierre-André K.',
    customerMessage: "Votre secrétaire m'a dit de vous appeler directement.",
    responseBefore: "Je vous passe directement ",
    responseAfter: " secrétaire pour qu'elle vous confirme le rendez-vous.",
    options: ['de la', 'à la', 'du', 'au'],
    correct: 'de la',
    explanation: "'de + la' = 'de la' (féminin, pas de contraction). 'du' = 'de + le' (masculin seulement). 'Secrétaire' est ici féminin.",
    points: 100,
    minLevel: 3,
  },
  {
    id: 'ortho-desole-accord',
    type: 'orthography',
    customerEmoji: '😡',
    customerName: 'Monique F.',
    customerMessage: "J'attends une réponse depuis 3 semaines ! C'est un scandale !",
    responseBefore: 'Nous sommes sincèrement ',
    responseAfter: ' pour ce délai inacceptable, madame.',
    options: ['désolés', 'désoler', 'désolé', 'désolées'],
    correct: 'désolés',
    explanation: "'Nous' = masculin pluriel (ou mixte) → 'désolés' (avec s, sans e). 'Nous sommes' → adjectif attribut qui s'accorde avec 'nous'.",
    points: 100,
    minLevel: 4,
  },
  {
    id: 'ortho-pret-a',
    type: 'orthography',
    customerEmoji: '⏰',
    customerName: 'Julien B.',
    customerMessage: "Je suis disponible dans 10 minutes pour un rappel.",
    responseBefore: "Parfait ! Nous sommes ",
    responseAfter: ' vous rappeler dès maintenant si vous le souhaitez.',
    options: ['prêts à', 'prêt à', 'prêts de', 'prêt de'],
    correct: 'prêts à',
    explanation: "'Prêts à' = 'nous' (pluriel, masculin ou mixte) + préposition 'à' devant un infinitif. 'Prêt de' ne s'emploie pas avec un infinitif.",
    points: 100,
    minLevel: 4,
  },
  {
    id: 'ortho-y-a-t-il',
    type: 'orthography',
    customerEmoji: '❓',
    customerName: 'Anonyme',
    customerMessage: "Il y a des frais supplémentaires ou pas ?",
    responseBefore: 'Non, ',
    responseAfter: " aucun frais caché dans notre offre.",
    options: ["il n'y a", "il n'y à", "il n'y as", "il n'y â"],
    correct: "il n'y a",
    explanation: "'Il y a' = verbe avoir. Seul 'a' (verbe) est correct ici. 'À' est une préposition, pas un verbe.",
    points: 100,
    minLevel: 4,
  },
  {
    id: 'ortho-quel-formulaire',
    type: 'orthography',
    customerEmoji: '🗂️',
    customerName: 'Hugues V.',
    customerMessage: "Je ne sais plus par où commencer pour régulariser ma situation.",
    responseBefore: '',
    responseAfter: " formulaire devez-vous remplir ? Celui disponible en ligne, rubrique 'Mon espace'.",
    options: ['Quel', 'Quelle', 'Quels', 'Quelles'],
    correct: 'Quel',
    explanation: "'Quel' s'accorde avec le nom qui suit. 'Formulaire' est masculin singulier → 'quel'. 'Quelle' serait pour un nom féminin ('quelle page').",
    points: 100,
    minLevel: 4,
  },
  {
    id: 'ortho-davantage',
    type: 'orthography',
    customerEmoji: '🤨',
    customerName: 'Lionel P.',
    customerMessage: "Je m'attendais à beaucoup mieux de votre part !",
    responseBefore: 'Nous ferons ',
    responseAfter: " d'efforts pour vous satisfaire, c'est notre engagement.",
    options: ['davantage', "d'avantage", 'davantages', "d'avantages"],
    correct: 'davantage',
    explanation: "'Davantage' = adverbe signifiant 'plus'. 'Avantage' est un nom (bénéfice, atout). On ne peut pas dire 'd'avantages' dans ce sens : ce serait 'nous ferons davantage d'efforts'.",
    points: 100,
    minLevel: 4,
  },
  {
    id: 'ortho-quoi-que',
    type: 'orthography',
    customerEmoji: '😒',
    customerName: 'Patricia F.',
    customerMessage: "Peu importe ce que vous me dites, je ne suis pas satisfaite !",
    responseBefore: '',
    responseAfter: ' il en soit, nous allons trouver une solution ensemble.',
    options: ["Quoi qu'", "Quoiqu'", "Quoi-qu'", 'Quoique'],
    correct: "Quoi qu'",
    explanation: "\"Quoi qu'il en soit\" (= quelle que soit la situation) s'écrit en deux mots séparés. \"Quoique\" (= bien que) est une conjonction : 'quoiqu'il soit tard'.",
    points: 100,
    minLevel: 5,
  },
  {
    id: 'ortho-ni-ni',
    type: 'orthography',
    customerEmoji: '😤',
    customerName: 'Roland B.',
    customerMessage: "Vos agents n'y connaissent rien, c'est consternant !",
    responseBefore: 'Je vous assure que ',
    responseAfter: " votre dossier ni votre demande ne sont passés inaperçus.",
    options: ['ni', 'ny', "n'y", 'nit'],
    correct: 'ni',
    explanation: "'Ni... ni...' = conjonction de coordination négative reliant deux éléments. 'N'y' = ne + y (pronom/adverbe). Ici on coordonne deux sujets → 'ni... ni...'.",
    points: 100,
    minLevel: 5,
  },
  {
    id: 'stats-appels-france',
    type: 'statistics',
    customerEmoji: '📞',
    customerName: 'Renaud D.',
    customerMessage: "Vous devez traiter des milliers d'appels, je comprends que ça prend du temps.",
    responseBefore: "Merci pour votre compréhension ! Les centres d'appel français traitent environ ",
    responseAfter: " appels entrants par an.",
    options: ['3 milliards', '500 000', '80 millions', '12 milliards'],
    correct: '3 milliards',
    explanation: "3 milliards d'appels sont traités chaque année dans les centres de relation client en France, soit plus de 8 millions par jour !",
    points: 80,
    minLevel: 4,
  },
  {
    id: 'stats-fautes-frappe',
    type: 'statistics',
    customerEmoji: '⌨️',
    customerName: 'Gilles M.',
    customerMessage: "Il y a encore une coquille dans votre dernier courriel !",
    responseBefore: "Toutes nos excuses ! En moyenne, un adulte fait ",
    responseAfter: " fautes de frappe pour 100 mots tapés.",
    options: ['3', '0', '22', '47'],
    correct: '3',
    explanation: "3 fautes pour 100 mots, c'est la moyenne observée pour un adulte qui tape à vitesse normale. Un correcteur orthographique en repère environ 60% automatiquement.",
    points: 80,
    minLevel: 5,
  },
  {
    id: 'ortho-tout-adverbe',
    type: 'orthography',
    customerEmoji: '😊',
    customerName: 'Isabelle R.',
    customerMessage: "Je veux juste m'assurer que tout est bien pris en compte.",
    responseBefore: 'Soyez ',
    responseAfter: " rassurée, madame, votre dossier est complet.",
    options: ['tout à fait', 'toute à fait', 'tous à fait', 'toutes à fait'],
    correct: 'tout à fait',
    explanation: "'Tout' devant un adjectif féminin reste invariable SAUF devant un adjectif commençant par une consonne ou un 'h' aspiré. Ici 'tout à fait' est une locution figée invariable.",
    points: 100,
    minLevel: 5,
  },

  // ── STATISTIQUES ──────────────────────────────────────────────────────────

  {
    id: 'stats-ses-ces',
    type: 'statistics',
    customerEmoji: '🤓',
    customerName: 'Prof. Durand',
    customerMessage: "Vous devriez faire des formations en orthographe pour vos agents !",
    responseBefore: 'Vous avez raison ! Sachez que ',
    responseAfter: " des Français adultes confondent régulièrement 'ses' et 'ces'.",
    options: ['62%', '5%', '91%', '18%'],
    correct: '62%',
    explanation: "62% des Français adultes confondent ces deux mots dans une situation de fatigue ou de rapidité. Vous n'êtes pas seul(e) !",
    points: 80,
    minLevel: 1,
  },
  {
    id: 'stats-clients-silencieux',
    type: 'statistics',
    customerEmoji: '😶',
    customerName: 'Didier S.',
    customerMessage: "J'aurais pu ne jamais appeler mais là c'était trop.",
    responseBefore: 'Nous vous remercions vraiment ! En fait, ',
    responseAfter: ' des clients mécontents ne se plaignent jamais et changent directement de prestataire.',
    options: ['96%', '30%', '55%', '12%'],
    correct: '96%',
    explanation: "96% des clients insatisfaits partent sans rien dire ! Vous faites partie des 4% qui nous permettent de nous améliorer.",
    points: 80,
    minLevel: 1,
  },
  {
    id: 'stats-emails-ouverts',
    type: 'statistics',
    customerEmoji: '📬',
    customerName: 'Caroline M.',
    customerMessage: "Je vous ai envoyé un mail il y a 10 jours, personne n'a répondu !",
    responseBefore: 'Toutes nos excuses. Vous avez bien fait d\'appeler car ',
    responseAfter: " des e-mails professionnels ne sont jamais ouverts.",
    options: ['23%', '3%', '71%', '50%'],
    correct: '23%',
    explanation: "23% des emails pros finissent dans les limbes sans jamais être ouverts. C'est pour ça qu'on recommande toujours de doubler par téléphone !",
    points: 80,
    minLevel: 1,
  },
  {
    id: 'stats-accord-participe',
    type: 'statistics',
    customerEmoji: '📚',
    customerName: 'Bertrand L.',
    customerMessage: "Même vos emails ont des fautes d'accord !",
    responseBefore: 'Nous travaillons là-dessus ! En France, ',
    responseAfter: " des adultes ont du mal avec l'accord du participe passé.",
    options: ['75%', '12%', '5%', '99%'],
    correct: '75%',
    explanation: "3 Français sur 4 trébuchent sur l'accord du participe passé. C'est officiellement la règle la plus redoutée du français !",
    points: 80,
    minLevel: 2,
  },
  {
    id: 'stats-appels-abandonnes',
    type: 'statistics',
    customerEmoji: '😤',
    customerName: 'Jérôme T.',
    customerMessage: "J'ai raccroché 4 fois avant que vous décrochiez !",
    responseBefore: 'Sincèrement désolés ! En moyenne, ',
    responseAfter: " des appelants raccrochent avant d'être pris en charge par un service client.",
    options: ['35%', '2%', '80%', '15%'],
    correct: '35%',
    explanation: "35% des appelants raccrochent avant d'être aidés. La patience des clients a des limites... surtout après la 3ème chanson d'attente.",
    points: 80,
    minLevel: 2,
  },
  {
    id: 'stats-sms-par-jour',
    type: 'statistics',
    customerEmoji: '📱',
    customerName: 'Léa B.',
    customerMessage: "Vous pouvez pas envoyer un SMS de confirmation ?",
    responseBefore: 'Absolument ! Vous seriez dans les ',
    responseAfter: " SMS envoyés chaque jour en France.",
    options: ['300 millions', '5 000', '3 milliards', '2 000'],
    correct: '300 millions',
    explanation: "300 millions de SMS sont envoyés quotidiennement en France. Les messageries (WhatsApp, iMessage) ont réduit ce chiffre depuis les années 2010.",
    points: 80,
    minLevel: 2,
  },
  {
    id: 'stats-sapins-vosges',
    type: 'statistics',
    customerEmoji: '🌲',
    customerName: 'René V.',
    customerMessage: "Je suis vosgien, j'ai hérité d'un terrain forestier !",
    responseBefore: 'Ah les Vosges ! Saviez-vous que la forêt vosgienne compte environ ',
    responseAfter: " arbres, majoritairement des sapins ?",
    options: ['95 millions', '500 000', '1 milliard', '3 millions'],
    correct: '95 millions',
    explanation: "La forêt vosgienne couvre 375 000 hectares et compte ~95 millions d'arbres. Le sapin pectiné y est roi !",
    points: 80,
    minLevel: 2,
  },
  {
    id: 'ortho-peut-etre',
    type: 'orthography',
    customerEmoji: '🤞',
    customerName: 'Sabine K.',
    customerMessage: "J'ai signalé le problème hier, est-ce qu'il a été traité ?",
    responseBefore: 'Votre demande ',
    responseAfter: " déjà en cours de traitement — je vérifie ça tout de suite !",
    options: ['est peut-être', 'est peut être', 'est peut-être-', 'est peut-être,'],
    correct: 'est peut-être',
    explanation: "'Peut-être' (adverbe de doute) s'écrit toujours avec un trait d'union. 'Peut être' (deux mots) = 'il peut être' (verbe pouvoir + infinitif être). Test : peut-on remplacer par 'il est possible que' ? Oui → trait d'union.",
    points: 100,
    minLevel: 3,
  },
  {
    id: 'stats-mensonge-medecin',
    type: 'statistics',
    customerEmoji: '🏥',
    customerName: 'Pascale N.',
    customerMessage: "Vous savez, moi je dis toujours la vérité !",
    responseBefore: 'C\'est admirable ! En comparaison, ',
    responseAfter: " des Français avouent mentir à leur médecin (tabac, alcool, alimentation...).",
    options: ['29%', '4%', '82%', '55%'],
    correct: '29%',
    explanation: "29% des Français mentent à leur médecin, surtout sur la consommation de tabac, d'alcool et les bonnes habitudes alimentaires.",
    points: 80,
    minLevel: 3,
  },
  {
    id: 'stats-a-a',
    type: 'statistics',
    customerEmoji: '✍️',
    customerName: 'Michel D.',
    customerMessage: "Même dans vos courriers vous écrivez mal !",
    responseBefore: "C'est une difficulté très répandue. ",
    responseAfter: " des adultes confondent 'a' (avoir) et 'à' (préposition) en situation de fatigue.",
    options: ['48%', '3%', '95%', '20%'],
    correct: '48%',
    explanation: "Près d'un Français sur deux fait cette erreur quand il écrit vite. Le cerveau en mode automatique choisit souvent la mauvaise graphie !",
    points: 80,
    minLevel: 3,
  },
  {
    id: 'stats-baguettes',
    type: 'statistics',
    customerEmoji: '🥖',
    customerName: 'Éric B.',
    customerMessage: "Je travaille dans une boulangerie, j'ai besoin d'une réponse vite !",
    responseBefore: 'On file vite alors ! Les boulangers comme vous fabriquent en tout ',
    responseAfter: " baguettes par jour en France.",
    options: ['16 millions', '500', '200 millions', '800 000'],
    correct: '16 millions',
    explanation: "16 millions de baguettes sont vendues chaque jour en France, dans les 35 000 boulangeries artisanales. Vive la baguette !",
    points: 80,
    minLevel: 3,
  },
  {
    id: 'stats-chat-reclamation',
    type: 'statistics',
    customerEmoji: '🐱',
    customerName: 'Valérie C.',
    customerMessage: "Mon chat a détruit ma box internet, donc je veux un remboursement !",
    responseBefore: 'Ah voilà une situation originale ! Et pourtant, ',
    responseAfter: ' des réclamations en France mentionnent réellement un animal comme responsable.',
    options: ['0,3%', '0,001%', '15%', '42%'],
    correct: '0,3%',
    explanation: "0,3% des réclamations impliquent un animal. Les chats représentent la majorité des cas, suivis des chiens et, plus rarement, des rongeurs câbleurs.",
    points: 80,
    minLevel: 4,
  },
  {
    id: 'stats-mails-travail',
    type: 'statistics',
    customerEmoji: '💻',
    customerName: 'Anne-Sophie T.',
    customerMessage: "Je reçois tellement de mails, j'ai failli rater votre réponse !",
    responseBefore: 'On comprend ! En moyenne, un actif français reçoit ',
    responseAfter: " e-mails professionnels par jour.",
    options: ['40', '5', '300', '1 200'],
    correct: '40',
    explanation: "Un salarié français reçoit en moyenne 40 emails professionnels par jour, dont 25% qui ne requièrent aucune action de sa part.",
    points: 80,
    minLevel: 4,
  },
  {
    id: 'stats-ronfleurs',
    type: 'statistics',
    customerEmoji: '😴',
    customerName: 'Rémi P.',
    customerMessage: "C'est mon voisin qui m'a réveillé pour que j'appelle !",
    responseBefore: 'Quelle solidarité ! Dites-lui que ',
    responseAfter: " de la population française ronfle de façon régulière.",
    options: ['40%', '3%', '85%', '12%'],
    correct: '40%',
    explanation: "40% des Français ronflent régulièrement. C'est beaucoup de voisins qui risquent de se faire réveiller en retour !",
    points: 80,
    minLevel: 4,
  },
  {
    id: 'stats-coca-buveur',
    type: 'statistics',
    customerEmoji: '🥤',
    customerName: 'Dylan S.',
    customerMessage: "J'appelle depuis La Baffe, ici on boit beaucoup de Coca !",
    responseBefore: 'Ah les connaisseurs ! La France consomme environ ',
    responseAfter: " canettes de boissons gazeuses par an.",
    options: ['6 milliards', '50 000', '1 trillion', '300 millions'],
    correct: '6 milliards',
    explanation: "6 milliards de canettes et bouteilles de sodas sont consommées en France chaque année. La Baffe doit y contribuer significativement !",
    points: 80,
    minLevel: 5,
  },
  {
    id: 'stats-appel-duree',
    type: 'statistics',
    customerEmoji: '⏳',
    customerName: 'Christian A.',
    customerMessage: "J'espère que ça va pas durer des heures, j'ai la famille qui attend !",
    responseBefore: "Je serai bref ! En moyenne, un appel service client dure ",
    responseAfter: " en France.",
    options: ['4 minutes', '45 secondes', '25 minutes', '1 heure'],
    correct: '4 minutes',
    explanation: "La durée moyenne d'un appel au service client est de 4 minutes en France. Le top du monde est détenu par... les administrations françaises (bien plus long) !",
    points: 80,
    minLevel: 5,
  },
];

// ── CONFIG PAR NIVEAU ─────────────────────────────────────────────────────

export const QUESTION_COUNT: Record<number, number> = {
  1: 4,
  2: 5,
  3: 6,
  4: 7,
  5: 8,
};

/** Score minimum pour valider le niveau */
export const WIN_SCORE: Record<number, number> = {
  1: 320,
  2: 480,
  3: 660,
  4: 880,
  5: 1200,
};

/** Temps alloué par question (secondes) */
export const QUESTION_TIME: Record<number, number> = {
  1: 30,
  2: 26,
  3: 22,
  4: 18,
  5: 14,
};
